### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jozz024** [Edclydson/MicrosoftRewardsScripyt#1]
Hello, i am attempting to use this, but every time i do i get this error:
Traceback (most recent call last):
  File "C:\Users\jozz0\Documents\Code\MicrosoftRewardsScripyt\main.py", line 38, in <module>
    run()
  File "C:\Users\jozz0\Documents\Code\MicrosoftRewardsScripyt\main.py", line 12, in run
    Action.Cookies.accept()
  File "C:\Users\jozz0\Documents\Code\MicrosoftRewardsScripyt\actions\actions.py", line 14, in accept
    .until(EC.presence_of_element_located((By.ID,
  File "C:\Users\jozz0\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00007FF6477EDF92+60274]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF64777EBF2+818946]
        (No symbol) [0x00007FF64740DFAE]
        (No symbol) [0x00007FF64744FAA1]
        (No symbol) [0x00007FF64744FC28]
        (No symbol) [0x00007FF64748B687]
        (No symbol) [0x00007FF64746F5AF]
        (No symbol) [0x00007FF647442751]
        (No symbol) [0x00007FF64748891C]
        (No symbol) [0x00007FF64746F343]
        (No symbol) [0x00007FF647441796]
        (No symbol) [0x00007FF647440975]
        (No symbol) [0x00007FF647441F04]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF6476827D7+1593703]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF64752AC5D+185837]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6476BFD47+36951]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6476B7E55+4453]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF6479BFDB3+1319011]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF647786CAC+851900]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF647782D14+835620]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF647782E6C+835964]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF647778A41+793937]
        BaseThreadInitThunk [0x00007FFDB4C4244D+29]
        RtlUserThreadStart [0x00007FFDB628DF78+40]
any help would be appreciated

**Comment by Edclydson** [comment]
Hey @jozz024 
I believe this happens because this:

> File "C:\Users\jozz0\Documents\Code\MicrosoftRewardsScripyt\actions\actions.py", line 14, in accept
.until(EC.presence_of_element_located((By.ID,

in this line, the webdriver will wait until the cookies popup shows up, but there's a limited time for that waiting ( I think is set to 5 seconds, but probably changing this will solve this error ), sometimes the web page could take too long to load completely and exceeding the time setted and consequently raising an exception.
